### PR TITLE
Add Ripple protocol and Ripple Desktop Wallet

### PR DESCRIPTION
**Pull request by john-light**

### CODE REVIEW

**Comment by eliooses** [comment]
Thanks, but no thanks.

**Comment by john-light** [comment]
@eliooses you have one Ripple project (The World Exchange) and a Ripple-derived project (Stellar) in your directory already. Why was this PR rejected?

**Comment by eliooses** [comment]
@john-light sorry, but i don´t have bad vibes with you. Is just because Rippex will shut down: http://blog.rippex.net/br/2018/02/gateway-closure/

But its, okey, i update with this note. Really thanks, and sorry for my previous message.

**Comment by john-light** [comment]
@eliooses worth noting that even though their gateway is shutting down, the desktop wallet I linked to should continue to work for as long as the Ripple network is operational. Gateway = centralized interface to the network, desktop wallet = decentralized interface to the network.

**Comment by eliooses** [comment]
Yeah, you are right @john-light the link is to the wallet and not to the gateway. #MyBad

I just updated with `operating ` status.

**Comment by eliooses** [comment]
Thanks again.

**Comment by eliooses** [comment]
I added the `DC` parameter to the DEX grade column.

**Pull request merged**
